name: Build & Deploy React to S3

on:
  push:
    branches: [ main, dev, fe-dev, fe/setting/\#93 ]

permissions:
  id-token: write
  contents: read

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ›  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies and ğŸ”¨ Build
        working-directory: frontend
        run: |
          echo "ğŸ“¦ Installing dependencies..."
          npm ci

          echo "ğŸ”¨ Building React app..."
          npm run build

      - name: ğŸ” Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ap-northeast-2

      - name: ğŸš€ Deploy to S3
        working-directory: frontend
        run: |
          echo "ğŸš€ Uploading to S3..."
          aws s3 sync dist/ s3://${{secrets.AWS_FE_BUCKET_NAME}} --delete --cache-control "max-age=0,no-cache,no-store,must-revalidate"
